### Try to get data without authentiucation
GET http://localhost:8080/api/v1/items
Accept: application/json

### Try to authenticate
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "admin-password"
}

### Try to authenticate after password is changed
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@mail.ru",
  "password": "newPassWord"
}

### Try to get data after success authentiucation
GET http://localhost:8080/api/v1/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYxMDg2NzQ3NCwiZXhwIjoxNjEwODY4MDc4fQ.WddyOYd4pMLqrdN0VLMZ-EWYkWKuGvr8vHaAFiKO6Uo
