PUT http://localhost:8080/api/v1/items/1003
Content-Type: application/json

{
  "name": "Moloko Вкусное?",
  "sku": "#moloko555",
  "supplier": {
    "id": 1000
  },
  "categories": [
    {
      "id": 1000
    }
  ]
}

###

DELETE http://localhost:8080/api/v1/items/1041

###

POST http://localhost:8080/api/v1/items
Content-Type: application/json

{
  "name": "Moloko Burenka2",
  "sku": "#moloko785",
  "supplier": {
    "id": 1001
  },
  "categories": [
    {
      "id": 1001
    }
  ],
  "unit": {
    "id": 1000
  },
  "storehouses_balance": [
    {
      "id": 1001,
      "quantity": 14
    },
    {
      "id": 1000,
      "quantity": 18
    }
  ]
}

###

GET http://localhost:8080/api/v1/items
Accept: application/json

###

GET http://localhost:8080/api/v1/items/1003
Accept: application/json

###

GET http://localhost:8080/api/v1/items/1
Accept: application/json

###

GET http://localhost:8080/api/v1/items?name=p
Accept: application/json

###

GET http://localhost:8080/api/v1/items?name=
Accept: application/json

###

###

GET http://localhost:8080/api/v1/items?page=1&size=5&sort=name,desc
Accept: application/json

###
