### READ all Storehouses

GET http://localhost:8080/api/v1/storehouses
Accept: application/json

### READ  Storehouse by id (id exists in table)

GET http://localhost:8080/api/v1/storehouses/1000
Accept: application/json

### READ Storehouse by id (id not exists in table)

GET http://localhost:8080/api/v1/storehouses/1
Accept: application/json

### READ all storehouses with "w" in name

GET http://localhost:8080/api/v1/storehouses?name=w
Accept: application/json

### READ all storehouses

GET http://localhost:8080/api/v1/storehouses?name=
Accept: application/json

### CREATE storehouses with id 1002

POST http://localhost:8080/api/v1/storehouses
Content-Type: application/json

{
  "name": "Test new storehouse"
}

### READ Storehouse by id 1002

GET http://localhost:8080/api/v1/storehouses?name=Test
Accept: application/json

### UPDATE Storehouse with id 1002

PUT http://localhost:8080/api/v1/storehouses/1002
Content-Type: application/json

{
  "name": "Test Storehouse"
}

### READ Storehouse by id 1002

GET http://localhost:8080/api/v1/storehouses/1002
Accept: application/json

### DELETE Storehouse with id 1002 - 405 answer

DELETE http://localhost:8080/api/v1/storehouses/1002

### GET All Items for Storehouse with id 1000

GET http://localhost:8080/api/v1/storehouses/1000/items

### GET All Items for Storehouse with id 9999

GET http://localhost:8080/api/v1/storehouses/9999/items

###