### READ all users
GET http://localhost:8080/api/v1/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYxMDg2NDIwNywiZXhwIjoxNjExNDY5MDA3fQ.jVVry1HAtyRdR3dVq5o_zw_VHpw7x4rPxllGQ6hPTf4

### READ all users
GET http://localhost:8080/api/v1/users?name=
Accept: application/json

### READ USER by id
GET http://localhost:8080/api/v1/users/1
Accept: application/json

### READ users with email containing admin
GET http://localhost:8080/api/v1/users?name=admin
Accept: application/json

### CREATE new user
POST http://localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYxMDg2NzY3MywiZXhwIjoxNjEwODY4Mjc3fQ.l2qmQ4heMp0ZsegJugQ-7JCCMN3SL1Bft6qZ-i3xnZA

{
  "email": "test1@mail.ru",
  "password": "passWord",
  "first_name": "TEST",
  "last_name": "TESTER",
  "role": "USER",
  "status": "ACTIVE"
}

### UPDATE user with id 1002
PUT http://localhost:8080/api/v1/users/1002
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYxMDg3MDA2NCwiZXhwIjoxNjEwODcwNjY5fQ.5pZSCP-C0cR_WgIjadbVrR9-j8cZ97nsSC6GeGJsR_w

{
  "email": "test@mail.ru",
  "password": "newPassWord",
  "first_name": "TEST_UPDATED",
  "last_name": "TESTER_UPDATED",
  "role": "USER",
  "status": "ACTIVE"
}

### DELETE user with id 4
DELETE http://localhost:8080/api/v1/users/4
Accept: application/json